<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Version>3.0.0</Version>
    <Title>CloudVoiceToText.NetCore</Title>
    <RepositoryUrl>https://github.com/XFEstudio/CloudVoiceToText</RepositoryUrl>
    <AnalysisLevel>latest</AnalysisLevel>
    <PackAsTool>False</PackAsTool>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <SignAssembly>True</SignAssembly>
    <Product>CloudVoiceToText.NetCore</Product>
    <Copyright>Copyright © 2023</Copyright>
    <Authors>XFEstudio</Authors>
    <Description>对接腾讯云的语音转文字的.NetCore版本</Description>
    <PackageProjectUrl>https://github.com/XFEstudio/CloudVoiceToText</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>XFE;VTT;Tencent;TencentCloud</PackageTags>
    <PackageReleaseNotes>
      更新对.NET 10.0的支持
    </PackageReleaseNotes>
    <OutputType>Library</OutputType>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="NAudio.Asio" Version="2.3.0" />
    <PackageReference Include="NAudio.Core" Version="2.3.0" />
    <PackageReference Include="NAudio.Midi" Version="2.3.0" />
    <PackageReference Include="NAudio.Wasapi" Version="2.3.0" />
    <PackageReference Include="NAudio.WinForms" Version="2.3.0" />
    <PackageReference Include="NAudio.WinMM" Version="2.3.0" />
    <PackageReference Include="XFEExtension.NetCore" Version="4.2.4-preview.1.1" />
    <PackageReference Include="XFEExtension.NetCore.AutoImplement" Version="1.1.0" />
  </ItemGroup>
</Project>